# Change these first
owner: CBMDF # Your GitHub username
repo: upptime # Your Github repository name
user-agent: cbmdf

# Add your sites here
sites:
  - name: Portal CBMDF
    url: https://www.cbm.df.gov.br
  - name: Sistemas CBMDF
    url: https://sistemas.cbm.df.gov.br
  - name: Cerberus OAuth2
    url: https://sistemas.cbm.df.gov.br/sistemas/cerberusAuth/public/oauth/
  - name: Web Mail
    url: https://cas.gdfnet.df.gov.br/owa
    __dangerous__insecure: true
  - name: Escalador
    url: https://escalador.cbm.df.gov.br
    __dangerous__insecure: true
  - name: SEIOP
    url: https://seiop.cbm.df.gov.br
    __dangerous__insecure: true
  - name: COVID-19
    url: https://sistemas.cbm.df.gov.br/covid
  - name: Inova
    url: https://singular.cbm.df.gov.br/inova/interno/login?0
    __dangerous__insecure: true
  - name: Portal Saúde
    url: https://saude.cbm.df.gov.br
  - name: Consulta Conveniados
    url: https://sistemas4.cbm.df.gov.br/pesquisahospitais/
    __dangerous__insecure: true
    __dangerous__body_down: "502 Bad Gateway"
  - name: SGO API Endereçamento
    url: $SGO_ENDERECAMENTO
    method: GET
    headers:
      - "X-Api-Key: $SGO_API_KEY"
    __dangerous__insecure: true
    __dangerous__body_down: "API_KEY_MISSING"
    
   
i18n:    
  activeIncidents: Incidentes ativos
  allSystemsOperational: Todos os sistemas estão em operação
  incidentReport: "Relatório do Incidente #$NUMBER →"
  activeIncidentSummary: Aberto em $DATE com $POSTS atualizações
  incidentTitle: Detalhes do Incidente $NUMBER
  incidentDetails: Detalhes do Incidente
  incidentFixed: Fixado
  incidentOngoing: Em andamento
  incidentOpenedAt: Aberto em
  incidentClosedAt: Fechado em
  incidentSubscribe: Inscreva-se para atualizações
  incidentViewOnGitHub: Visualizar no GitHub
  incidentCommentSummary: Publicado em $DATE por $AUTHOR
  incidentBack: ← Voltar para todos os incidentes
  pastIncidents: Incidentes Anteriores
  pastIncidentsResolved: Solucionado em $MINUTES minutos com $POSTS atualizações
  liveStatus: Live Status
  overallUptime: "Disponibilidade geral: $UPTIME"
  overallUptimeTitle: Disponibilidade Geral
  averageResponseTime: "Tempo médio de resposta: $TIMEms"
  averageResponseTimeTitle: Média de Resposta
  sevelDayResponseTime: Tempo de Resposta (últimos 07 dias)
  responseTimeMs: Tempo de resposta (ms)
  up: Ativo
  down: Indisponível
  degraded: Problemas de desempenho
  ms: ms
  loading: Carregando
  navGitHub: GitHub
  footer: This page is [open source]($REPO), powered by [Upptime](https://upptime.js.org)
  rateLimitExceededTitle: Taxa limite excedida
  rateLimitExceededIntro: You have exceeded the number of requests you can do in an hour, so you'll have to wait before accessing this website again. Alternately, you can add a GitHub Personal Access Token to continue to use this website.
  rateLimitExceededWhatDoesErrorMean: O que significa este erro?
  rateLimitExceededErrorMeaning: This website uses the GitHub API to access real-time data about our websites' status. By default, GitHub allows each IP address 60 requests per hour, which you have consumed.
  rateLimitExceededErrorHowCanFix: Como posso corrigir isto?
  rateLimitExceededErrorFix: You can wait for another hour and your IP address' limit will be restored. Alternately, you can add your GitHub Personal Access Token, which gives you an additional 5,000 requests per hour.
  rateLimitExceededGeneratePAT: Learn how to generate a Personal Access Token
  rateLimitExceededHasSet: You have a personal access token set.
  rateLimitExceededRemoveToken: Remove token
  rateLimitExceededGitHubPAT: GitHub Personal Access Token
  rateLimitExceededCopyPastePAT: Copy and paste your token
  rateLimitExceededSaveToken: Save token
  errorTitle: Ocorreu um erro
  errorIntro: Ocorreu um erro ao tentar obter os últimos detalhes de status.
  errorText: Você pode tentar novamente em instantes.
  errorHome: Ir para página inicial
  pastScheduledMaintenance: Manutenções Agendadas Passadas
  scheduledMaintenance: Manutenção Agendada
  scheduledMaintenanceSummaryStarted: Iniciada em $DATE por $DURATION minutos
  scheduledMaintenanceSummaryStarts: Inicia em $DATE por $DURATION minutos
  startedAt: Iniciado em
  startsAt: Inicia em
  duration: Duração
  durationMin: $DURATION minutos
  incidentCompleted: Concluído
  incidentScheduled: Agendado

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://www.cbm.df.gov.br/las-E4I9_256.png
  name: CBMDF Status Page
  introTitle: "**Upptime** é uma aplicação de código-aberto para monitoramento e informação de status serviços."
  introMessage: "Esta instalação está sendo utilizada para monitorar e informar sobre o status de serviços do Corpo de Bombeiros Militar do Distrito Federal (CBMDF)."
  navbar:
    - title: Página Inicial
      href: /upptime
    - title: Repositório
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
